{:ok, _app} = Application.ensure_all_started(:ex_machina)
ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(PurseCraft.Repo, :manual)
Faker.start()

Mimic.copy(PurseCraft.Budgeting.Policy)
Mimic.copy(PurseCraft.Budgeting)
Mimic.copy(PurseCraft.PubSub.BroadcastBook)
Mimic.copy(PurseCraft.Budgeting.Commands.PubSub.BroadcastCategory)
Mimic.copy(PurseCraft.Budgeting.Commands.PubSub.BroadcastUserBook)
Mimic.copy(PurseCraft.Budgeting.Commands.Categories.RepositionCategory)
Mimic.copy(PurseCraft.Budgeting.Commands.Envelopes.RepositionEnvelope)
Mimic.copy(PurseCraft.Budgeting.Repositories.CategoryRepository)
Mimic.copy(PurseCraft.Budgeting.Repositories.EnvelopeRepository)
Mimic.copy(PurseCraft.Accounting.Repositories.AccountRepository)
