{:ok, _app} = Application.ensure_all_started(:ex_machina)
ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(PurseCraft.Repo, :manual)
Faker.start()

Mimic.copy(PurseCraft.Budgeting.Policy)
Mimic.copy(PurseCraft.Budgeting)
Mimic.copy(PurseCraft.Core.Policy)
Mimic.copy(PurseCraft.Core)
Mimic.copy(PurseCraft.Core.Commands.Workspaces.FetchWorkspaceByExternalId)
Mimic.copy(PurseCraft.Core.Commands.Workspaces.DeleteWorkspace)
Mimic.copy(PurseCraft.PubSub.BroadcastWorkspace)
Mimic.copy(PurseCraft.PubSub.BroadcastCategory)
Mimic.copy(PurseCraft.PubSub.BroadcastUserWorkspace)
Mimic.copy(PurseCraft.Budgeting.Commands.Categories.RepositionCategory)
Mimic.copy(PurseCraft.Budgeting.Commands.Envelopes.RepositionEnvelope)
Mimic.copy(PurseCraft.Budgeting.Repositories.CategoryRepository)
Mimic.copy(PurseCraft.Budgeting.Repositories.EnvelopeRepository)
Mimic.copy(PurseCraft.Accounting)
Mimic.copy(PurseCraft.Accounting.Repositories.AccountRepository)
Mimic.copy(PurseCraft.Core.Commands.Workspaces.FetchWorkspace)
Mimic.copy(PurseCraft.Search.Commands.Token.UpdateTokens)
Mimic.copy(PurseCraft.Search.Commands.Token.DeleteTokens)
Mimic.copy(PurseCraft.PubSub)
